

$(eval $(call provider_rules_template,gals_heat_protocol_only))


gals_heat_protocol_only_tests : $(ALL_gals_heat_protocol_only_TESTS)

gals_heat_protocol_only_demos : $(ALL_gals_heat_protocol_only_DEMOS)

ALL_TESTS += gals_heat_protocol_only_tests

ALL_DEMOS += gals_heat_protocol_only_demos



